services:
  api:
    build:
      context: .
      target: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      target: streamlit
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - .:/app
